routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/public/public',function(){
    return view('welcome');
});
Route::get('/phpinfo',function(){ 
    phpinfo();
});

Route::group([
    'prefix' => 'client',
    'namespace' => 'Client'
], function(){
    Auth::routes(['register' => false]);
    Route::get('/', 'HomeController@index')->name('client.home');
    Route::get('/riders', 'RiderController@showRiders')->name('client.riders');
    Route::get('/riders/locations', 'RiderController@showAllRidersLocations')->name('client.riders.locations');
    Route::get('/rider/{rider}/location', 'RiderController@showRiderLocation')->name('client.rider.location');
    Route::get('/profile', 'ProfileController@showProfile')->name('client.profile');
    Route::get('/profile/edit', 'ProfileController@edit')->name('client.profile.edit');
    Route::put('/profile', 'ProfileController@update')->name('client.profile.update');
    Route::get('/messageToSupport', 'ProfileController@messageToSupport')->name('client.messageToSupport');
    Route::post('/messageToSupport', 'ProfileController@sendMessageToSupport')->name('client.sendMessageToSupport');
    Route::post('/update/client/riders','RiderController@update_ClientRiders')->name('ClientRiders.update');
});

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin'
], function(){
    Route::post('/update/client/riders','RiderController@update_ClientRiders')->name('ClientRiders.admin.update');
    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\LoginController@login')->name('admin.login');
    Route::get('/logout', 'Auth\LoginController@logout')->name('admin.logout');
    Route::get('/rider/salary','RiderController@rider_salary')->name('Rider.salary');
    Route::get('/', 'HomeController@index')->name('admin.home');
    Route::get('/livemap', 'HomeController@livemap')->name('admin.livemap');
    Route::get('/profile', 'HomeController@profile')->name('admin.profile');
    Route::put('/profile', 'HomeController@updateProfile')->name('admin.profile.update');

    // AJAX Routes
    Route::get('/clients/data', 'AjaxController@getClients')->name('admin.clients.data');
    Route::get('/riders/data', 'AjaxController@getRiders')->name('admin.riders.data');
    Route::get('/riders/{rider}/ridesReport/data', 'AjaxController@getRidesReport')->name('admin.ridesReport.data');
    // Route::get('/rider/{rider}/messages/data', 'AjaxController@getMessages')->name('admin.rider.messages.data');
  
    Route::resource('/riders', 'RiderController', [
        'as' => 'admin'
    ]);
    Route::get('/rider/{rider}/location', 'RiderController@showRiderLocation')->name('admin.rider.location');
    Route::get('/rider/{rider}/profile', 'RiderController@showRiderProfile')->name('admin.rider.profile');

    Route::get('/rider/{rider}/ridesReport', 'RiderController@showRidesReport')->name('admin.rider.ridesReport');
    Route::delete('/ridesReportRecord/{record}', 'RiderController@deleteRidesReportRecord')->name('admin.rider.ridesReport.delete');

    Route::post('/rider/{rider}/sendMessage', 'RiderController@sendSMS')->name('admin.rider.sendSMS');
    Route::post('/rider/{rider}/updateStatus', 'RiderController@updateStatus')->name('admin.rider.updateStatus');
    // Route::get('/rider/{rider}/messages', 'RiderController@showMessages')->name('admin.rider.messages');
    Route::get('/client/rider/performance','RiderController@RiderPerformance')->name('admin.riderPerformance');
    Route::get('get/ajax/rider/performance','AjaxController@getRiderPerformance')->name('admin.ajax_performance');
    Route::resource('/clients', 'ClientController', [
        'as' => 'admin'
    ]);
    Route::resource('/bikes', 'ClientController', [
        'as' => 'admin'
    ]);
    Route::get('/client/{client}/profile', 'ClientController@showClientProfile')->name('admin.client.profile');
    Route::get('/client/{client}/riders', 'ClientController@showRiders')->name('admin.clients.riders');
    Route::get('/client/{client}/assignRider', 'ClientController@assignRiders')->name('admin.clients.assignRiders');
    Route::put('/client/{client}/assignRider', 'ClientController@updateAssignedRiders')->name('admin.clients.assignRiders');
    Route::delete('/client/{client}/removeRider/{rider}', 'ClientController@removeRiders')->name('admin.clients.removeRiders');
    Route::post('/client/{client}/updateStatus', 'ClientController@updateStatus')->name('admin.client.updateStatus');
    Route::post('/client/mutlipleDelete', 'ClientController@mutlipleDelete')->name('admin.client.mutlipleDelete');

    // Client Email Route
    Route::resource('emails', 'ClientEmailController', [
        'as' => 'admin'
    ]);
});
Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin'
], function(){
    // Bike
    Route::get('/bike_login','bikeController@bike_login')->name('bike.bike_login');
    Route::post('/bike_create','bikeController@create_bike')->name('bike.bike_create');
    Route::get('/bike_getData','AjaxController@getBikes')->name('bike.bike_show');
    Route::get('/bike_view','bikeController@bike_view')->name('bike.bike_view');
    // Route::get('/bike_assigned','bikeController@bike_assigned_form')->name('bike.bike_assigned');
    Route::get('/bike/{bike}/assigned', 'ClientController@bike_assigned_show')->name('bike.bike_assigned');
    Route::get('/bike/{id}/assignRider', 'ClientController@bike_assigned_toRider')->name('bike.bike_assignRiders');
    Route::put('/bike/{rider}/assignRider', 'ClientController@updateAssignedBike')->name('bike.bike_assignRiders');
    Route::delete('/rider/{rider_id}/removeBike/{bike_id}', 'ClientController@removeBikes')->name('admin.removeBikes');
    Route::post('/bike/{bike}/updateStatus', 'ClientController@updateStatusbike')->name('bike.updateStatusbike');
    Route::delete('/bike/{bike_id}', 'ClientController@mutlipleDeleteBike')->name('bike.mutlipleDeleteBike');
    Route::get('/bike/Edit/{id}','bikeController@bike_edit')->name('Bike.edit_bike');
    Route::post('/bike/update/{id}','bikeController@bike_update')->name('Bike.bike_update');
    // Route::get('/bike/assigned/show/','ClientController@bike_is_show')->name('bike.bike_show');
    Route::get('/riders/{rider}/history','ClientController@Bike_assigned_to_riders_history')->name('Bike.assignedToRiders_History');
    Route::get('/bike/{bike_id}/history','ClientController@rider_history')->name('bike.rider_history');
    Route::get('/bike/{bike_id}/profile/{rider_id}','ClientController@bike_profile')->name('bike.bike_profile');
    // end Bike
});

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin'
], function(){
    // accounts
    Route::resource('/account', 'AccountsController', [
        'as' => 'admin'
    ]);
    // add_new_salary
    Route::get('/Add/Salary','AccountsController@add_new_salary_create')->name('account.new_salary');
    Route::post('/Salary/Added','AccountsController@new_salary_added')->name('account.added_salary');
    // end_add_new_salary

    //Mobiles
    Route::get('/mobile/create','MobileController@create_mobile_GET')->name('mobile.create_mobile_GET');
    Route::post('/mobile/create','MobileController@create_mobile_POST')->name('mobile.create_mobile_POST');
    Route::get('/mobiles','MobileController@mobiles')->name('mobile.show');
    Route::get('/mobile/{mobile}/edit','MobileController@update_mobile_GET')->name('mobile.edit');
    Route::get('/mobile/data','AjaxController@getMobiles')->name('mobile.getMobiles');
    Route::delete('/mobile/delete/{mobile_id}','MobileController@delete_mobile')->name('Mobile.delete_mobile');
    Route::post('/mobile/{id}/updateStatus','MobileController@updateStatusMobile')->name('Mobile.updatetatus');
    Route::post('/mobile/{id}/update','MobileController@update_mobile')->name('Mobile.update');
    //end Mobiles
    // mobile installement
    Route::get('/mobile/installment/create','MobileController@create_mobileInstallment')->name('MobileInstallment.create');
    Route::post('/mobile/installment/insert','MobileController@store_mobileInstallment')->name('MobileInstallment.store');
    Route::get('/mobile/installment/data','AjaxController@getMobileInstallment')->name('MobileInstallment.getinstallments');
    Route::get('/mobile/installment/show','MobileController@show_mobileInstallmenet')->name('MobileInstallment.show');
    Route::get('/mobile/installment/{mobile}/edit','MobileController@edit_mobileInstallment')->name('MobileInstallment.edit');
    Route::post('/mobile/installment/{id}/update','MobileController@update_mobileInstallment')->name('MobileInstallment.update');
    Route::delete('/mobile/installment/delete/{mobile_id}','MobileController@delete_mobileInstallment')->name('MobileInstallment.delete');
    // end mobile installement
    Route::get('/a/{id}','AjaxController@rider_name');
    
    Route::delete('/month/{month_id}', 'AccountsController@DeleteMonth')->name('account.DeleteMonth');
    Route::get('/Month/Salary','AccountsController@salary_by_month_create')->name('account.month_salary');
    Route::post('/month/{month_id}/updateStatus', 'AccountsController@updateStatusmonth')->name('account.updateStatusmonth');
    Route::get('/month/Edit/{month_id}','AccountsController@month_edit')->name('account.edit_month');
    Route::post('/month/update/{month_id}','AccountsController@month_update')->name('account.month_update');
    
//    developer salary
    Route::get('/Developer/Salary/ajax','AjaxController@getSalary_by_developer')->name('account.developer_salary_ajax');

app/Http/Controllers/Client/HomeController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('client.home');
    }

    public function showRiders()
    {
        $riders = Auth::user()->riders;
        // return $riders;
        return view('client.rider.riders', compact('riders'));
    }
}

app/Http/Controllers/Client/ProfileController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use App\Model\Admin\Client_Email;

class ProfileController extends Controller
{
    //
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function showProfile()
    {
        $user = Auth::user();
        return view('client.profile.profile', compact('user'));
    }
    public function edit()
    {
        $user = Auth::user();
        return view('client.profile.edit', compact('user'));
    }
    public function update(Request $request)
    {
        $user = Auth::user();
        $this->validate($request, [
            'name' => 'required | string',
            'email' => 'required | email',
            'phone' => 'required | string',
            'address' => 'required | string',
        ]);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->phone = $request->phone;
        // $user->about = $request->about;
        $user->address = $request->address;
        if($request->hasFile('logo'))
        {
            // return 'yes';
            if($user->logo)
            {
                Storage::delete($user->logo);
            }
            $filename = $request->logo->getClientOriginalName();
            $filesize = $request->logo->getClientSize();
            $filepath = Storage::putfile('public/uploads/clients/logos', $request->file('logo'));
            $user->logo = $filepath;
        }
        // return 'no';
        $user->update();
        return redirect(route('client.profile'));
    }
    public function messageToSupport()
    {
        return view('client.profile.messageToSupport');
    }
    public function sendMessageToSupport(Request $request)
    {
        $this->validate($request, [
            'from' => 'required | email',
            'subject' => 'required | string',
            'message' => 'required | string'
        ]);
        $email = new Client_Email();
        $email->from = $request->from;
        $email->subject = $request->subject;
        $email->message = $request->message;
        $email->save();
        return redirect()->back()->with('message', 'You message has been sent successfully.');
    }
}

app/Http/Controllers/Client/RiderController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Model\Rider\Rider;
use App\Model\Client\Client;
use App\Model\Client\Client_Rider;

class RiderController extends Controller
{
    //
    public function showAllRidersLocations()
    {
        return view('client.rider.allRidersLocations');
    }
    public function showRiders(Request $request)
    {
        $total_riders = Auth::user()->riders->count();
        $riders = Auth::user()->riders;
        
        return view('client.rider.riders', compact('riders', 'total_riders'));
    }
    public function showRiderLocation(Rider $rider)
    {
        return view('client.rider.location');
    }
   public function update_ClientRiders(Request $req){
        $client_rider=Client_Rider::where('client_id',Auth::user()->id)->where('rider_id',$req->rider_id)->get()->first();
        $client_rider->client_rider_id=$req->client_rider_id;
        $client_rider->update();
        return $client_rider;
   }
}

resources/views/admin/client/assignRider.blade.php
@extends('admin.layouts.app')
@section('main-content')
<!-- begin:: Content -->
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="row">
        <div class="col-md-12">
        <!--begin::Portlet-->
            <div class="kt-portlet">
                <div class="kt-portlet__head">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                            Assign Riders - <a href="{{ route('admin.clients.riders', $client->id) }}">{{ $client->name }}</a>
                        </h3>
                    </div>
                </div>

                <!--begin::Form-->
                
                @include('client.includes.message')
                <form class="kt-form" action="{{ route('admin.clients.assignRiders', $client->id) }}" method="POST" enctype="multipart/form-data">
                    {{ method_field('PUT') }}
                    {{ csrf_field() }}
                    <div class="kt-portlet__body">
                        <div class="form-group">
                            <label>Riders: </label>
                            <div>
                                <select class="form-control kt-select2" id="kt_select2_3" name="riders[]" multiple="multiple">
                                @foreach ($riders as $rider)
                                    <option value="{{ $rider->id }}" 
                                        {{-- @foreach ($client->getRiders as $assigned_rider)
                                            @if($rider->id == $assigned_rider->id)
                                                selected = "selected"
                                            @endif
                                        @endforeach --}}
                                    >{{ $rider->name }} </option>
                                @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="kt-portlet__foot">
                        <div class="kt-form__actions kt-form__actions--right">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <span class="kt-margin-l-10">or <a href="{{ route('admin.clients.index') }}" class="kt-link kt-font-bold">Cancel</a></span>
                        </div>
                    </div>
                </form>

                <!--end::Form-->
            </div>

        <!--end::Portlet-->
    </div>
</div>
@endsection
@section('foot')
    <script src="{{ asset('dashboard/assets/js/demo1/pages/crud/forms/widgets/select2.js') }}" type="text/javascript"></script>
@endsection

resources/views/admin/client/clients.blade.php
@extends('admin.layouts.app')
@section('head')
    <!--begin::Page Vendors Styles(used by this page) -->
    <link href="{{ asset('dashboard/assets/vendors/custom/datatables/datatables.bundle.css') }}" rel="stylesheet" type="text/css" />
    <style>
        .dataTables_length{
           display: block;   
        }
        .total_entries{
        display: inline-block;
        margin-left: 10px;
        }
        .dataTables_info{
            display:none;
        }
        </style>
    <!--end::Page Vendors Styles -->
@endsection
@section('main-content')
<!-- begin:: Content -->
@include('admin.includes.message')
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <span class="kt-portlet__head-icon">
                    <i class="kt-font-brand fa fa-hotel"></i>
                </span>
                <h3 class="kt-portlet__head-title">
                    Clients
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
                    <div class="kt-portlet__head-actions">
                        {{-- <button class="btn btn-danger btn-elevate btn-icon-sm" id="bulk_delete">Delete Selected</button> --}}
                        &nbsp;
                        <a href="{{ route('admin.clients.create') }}" class="btn btn-brand btn-elevate btn-icon-sm">
                            <i class="la la-plus"></i>
                            New Record
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="kt-portlet__body">

            <!--begin: Datatable -->
            <table class="table table-striped- table-hover table-checkable table-condensed" id="clients-table">
                <thead>
                    <tr>
                        {{-- <th>
                            <input type="checkbox" id="select_all" >
                        </th> --}}
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>City</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
            </table>

            <!--end: Datatable -->
        </div>
    </div>
</div>

<!-- end:: Content -->
@endsection
@section('foot')
<!--begin::Page Vendors(used by this page) -->
<script src="{{ asset('dashboard/assets/vendors/custom/datatables/datatables.bundle.js') }}" type="text/javascript"></script>

<!--end::Page Vendors -->

<!--begin::Page Scripts(used by this page) -->
<script src="{{ asset('dashboard/assets/js/demo1/pages/crud/datatables/basic/basic.js') }}" type="text/javascript"></script>

<!--end::Page Scripts -->
<script>
var clients_table;
$(function() {
    clients_table = $('#clients-table').DataTable({
        processing: true,
        serverSide: true,
        'language': {
            'loadingRecords': '&nbsp;',
            'processing': $('.loading').show()
        },
        drawCallback:function(data){
            $('.total_entries').remove();
        $('.dataTables_length').append('<div class="total_entries">'+$('.dataTables_info').html()+'</div>');
    },
        ajax: '{!! route('admin.clients.data') !!}', 
        columns: [
            // { data: 'checkbox', name: 'checkbox', orderable: false, searchable: false },
            { data: 'new_id', name: 'new_id' },
            { data: 'new_name', name: 'name' },
            { data: 'new_email', name: 'email' },
            { data: 'new_phone', name: 'phone' },
            { data: 'address', name: 'address' },
            { data: 'status', name: 'status' },
            { data: 'actions', name: 'actions', orderable: false, searchable: false }
        ],
        responsive:true,
        // 'columnDefs': [
        //     {
        //         'targets': 0,
        //         'checkboxes': {
        //         'selectRow': true
        //         }
        //     }
        // ],
        // 'select': {
        //     'style': 'multi'
        // },
        order:[0,'desc'],
    });
   
});
function deleteClient(id)
{
    var url = "{{ url('admin/clients') }}"+ "/" + id;
    sendDeleteRequest(url, false, null, clients_table);
}
function updateStatus(client_id)
{
    var url = "{{ url('admin/client') }}" + "/" + client_id + "/updateStatus";
    swal.fire({
        title: 'Are you sure?',
        text: "You want update status!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Yes!'
    }).then(function(result) {
        if (result.value) {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                url : url,
                type : 'POST',
                beforeSend: function() {            
                    $('.loading').show();
                },
                complete: function(){
                    $('.loading').hide();
                },
                success: function(data){
                    swal.fire({
                        position: 'center',
                        type: 'success',
                        title: 'Record updated successfully.',
                        showConfirmButton: false,
                        timer: 1500
                    });
                    clients_table.ajax.reload(null, false);
                },
                error: function(error){
                    swal.fire({
                        position: 'center',
                        type: 'error',
                        title: 'Oops...',
                        text: 'Unable to update.',
                        showConfirmButton: false,
                        timer: 1500
                    });
                }
            });
        }
    });
}
// $(document).on('click', '#bulk_delete', function(){
//     var id=[];
//     $('.client_checkbox:checked').each(function(){
//         id.push($(this).val());
//     });
//     if(id.length > 0)
//     {
//         var url = "{{ route('admin.client.mutlipleDelete') }}";
//         swal.fire({
//             title: 'Are you sure?',
//             text: "You want udpate status!",
//             type: 'warning',
//             showCancelButton: true,
//             confirmButtonText: 'Yes!'
//         }).then(function(result) {
//             if (result.value) {
//                 $.ajaxSetup({
//                     headers: {
//                         'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
//                     }
//                 });
//                 $.ajax({
//                     url : url,
//                     type : 'POST',
//                     data : {
//                         id : id
//                     },
//                     beforeSend: function() {            
//                         $('.loading').show();
//                     },
//                     complete: function(){
//                         $('.loading').hide();
//                     },
//                     success: function(data){
//                         swal.fire({
//                             position: 'center',
//                             type: 'success',
//                             title: 'Records deleted successfully.',
//                             showConfirmButton: false,
//                             timer: 1500
//                         });
//                         clients_table.ajax.reload(null, false);
//                     },
//                     error: function(error){
//                         swal.fire({
//                             position: 'center',
//                             type: 'error',
//                             title: 'Oops...',
//                             text: 'Unable to delete.',
//                             showConfirmButton: false,
//                             timer: 1500
//                         });
//                     }
//                 });
//             }
//         });
//     }
//     else
//     {
//         swal.fire("Nothing Selected!", "Please select atleast one record.", "warning");
//     }
// });
// $(document).ready(function () {
//     // $( "#select_all").prop('checked', true);
//     $('#select_all').change(function (){
//         if($('#select_all').prop("checked") == true)
//         {
//             var cb_array = document.getElementsByClassName('client_checkbox');
//             for(var i = 0; i < cb_array.length; i++)
//             {
//                 cb_array[i].checked = true;
//             }
//         }
//         else if($('#select_all').prop("checked") == false){
//             var cb_array = document.getElementsByClassName('client_checkbox');
//             for(var i = 0; i < cb_array.length; i++)
//             {
//                 cb_array[i].checked = false;
//             }
//         }
//     });
    
// });
</script>
@endsection